#!/usr/bin/env elixir

defmodule ToolchainVersionUpdater do
  @toolchain_config_path Path.expand("toolchain_config.exs")
  @output_path Path.expand("configs/toolchain_versions.exs")
  @host_fragment Path.expand("template/defaults/linux_x86_64_defconfig")
  @excluded_version_keys MapSet.new(["CT_CONFIG_VERSION", "CT_TOOLCHAIN_PKGVERSION"])
  @preferred_order [
    "CT_GCC_VERSION",
    "CT_BINUTILS_VERSION",
    "CT_LINUX_VERSION",
    "CT_GLIBC_VERSION",
    "CT_MUSL_VERSION",
    "CT_GDB_VERSION",
    "CT_EXPAT_VERSION",
    "CT_GETTEXT_VERSION",
    "CT_GMP_VERSION",
    "CT_ISL_VERSION",
    "CT_LIBICONV_VERSION",
    "CT_MPC_VERSION",
    "CT_MPFR_VERSION",
    "CT_NCURSES_VERSION",
    "CT_ZLIB_VERSION"
  ]
  @labels %{
    "CT_GCC_VERSION" => "GCC",
    "CT_BINUTILS_VERSION" => "binutils",
    "CT_BISON_VERSION" => "bison",
    "CT_LINUX_VERSION" => "Linux headers",
    "CT_GLIBC_VERSION" => "glibc",
    "CT_MUSL_VERSION" => "musl",
    "CT_GDB_VERSION" => "GDB",
    "CT_EXPAT_VERSION" => "expat",
    "CT_GETTEXT_VERSION" => "gettext",
    "CT_GMP_VERSION" => "GMP",
    "CT_ISL_VERSION" => "ISL",
    "CT_LIBICONV_VERSION" => "libiconv",
    "CT_M4_VERSION" => "m4",
    "CT_MPC_VERSION" => "MPC",
    "CT_MPFR_VERSION" => "MPFR",
    "CT_NCURSES_VERSION" => "ncurses",
    "CT_ZLIB_VERSION" => "zlib"
  }

  def main(_argv) do
    toolchain_config = load_toolchain_config!()
    ctng = ensure_ctng!(Map.fetch!(toolchain_config, :ctng_tag))

    version_metadata =
      "configs/nerves_toolchain_*"
      |> Path.wildcard()
      |> Enum.sort()
      |> Enum.map(&resolve_toolchain_versions(&1, ctng))
      |> Enum.into(%{})

    File.write!(@output_path, render(version_metadata))
  end

  defp resolve_toolchain_versions(config_dir, ctng) do
    app_name = Path.basename(config_dir)
    merged_defconfig = merge_defconfigs(config_dir)
    tmp_dir = System.tmp_dir!() |> Path.join("toolchain-version-#{app_name}-#{System.unique_integer([:positive])}")

    try do
      File.mkdir_p!(tmp_dir)
      File.write!(Path.join(tmp_dir, "defconfig"), merged_defconfig)

      {output, 0} = System.cmd(ctng, ["defconfig"], cd: tmp_dir, stderr_to_stdout: true)
      _ = output

      config = File.read!(Path.join(tmp_dir, ".config"))
      {app_name, extract_versions(config)}
    after
      File.rm_rf!(tmp_dir)
    end
  end

  defp merge_defconfigs(config_dir) do
    [Path.join(config_dir, "defconfig"), @host_fragment]
    |> Enum.map(&File.read!/1)
    |> Enum.join()
  end

  defp extract_versions(config) do
    versions =
      Regex.scan(~r/^(CT_[A-Z0-9_]+VERSION)="([^"]+)"$/m, config, capture: :all_but_first)
      |> Enum.reject(fn [key, _value] -> MapSet.member?(@excluded_version_keys, key) end)
      |> Map.new(fn [key, value] -> {key, value} end)

    ordered_keys =
      @preferred_order ++
        (versions
         |> Map.keys()
         |> Enum.reject(&(&1 in @preferred_order))
         |> Enum.sort())

    ordered_keys
    |> Enum.flat_map(fn key ->
      case Map.fetch(versions, key) do
        {:ok, value} -> [{Map.get(@labels, key, key), value}]
        :error -> []
      end
    end)
  end

  defp render(version_metadata) do
    entries =
      version_metadata
      |> Enum.sort_by(fn {app_name, _versions} -> app_name end)
      |> Enum.map_join(",\n", fn {app_name, versions} ->
        rendered_versions =
          versions
          |> Enum.map_join(",\n", fn {component, version} ->
            "    {#{inspect(component)}, #{inspect(version)}}"
          end)

        "  #{inspect(app_name)} => [\n#{rendered_versions}\n  ]"
      end)

    """
    # Generated by update_toolchain_versions.exs
    %{
    #{entries}
    }
    """
  end

  defp missing_ctng! do
    raise "failed to build crosstool-ng"
  end

  defp load_toolchain_config! do
    {config, _bindings} = Code.eval_file(@toolchain_config_path)

    if is_map(config) and is_binary(Map.get(config, :ctng_tag)) do
      config
    else
      raise "toolchain_config.exs must return a map with a :ctng_tag string"
    end
  end

  defp ensure_ctng!(ctng_tag) do
    install_dir = Path.join([home_dir!(), ".nerves", "ct-ng", ctng_tag])
    ctng = Path.join([install_dir, "bin", "ct-ng"])

    if File.exists?(ctng) do
      ctng
    else
      build_ctng!(ctng_tag, install_dir)
    end
  end

  defp build_ctng!(ctng_tag, install_dir) do
    work_dir = Path.join(System.tmp_dir!(), "toolchain-version-updater-#{System.unique_integer([:positive])}")
    source_dir = Path.join(work_dir, "crosstool-ng-#{ctng_tag}")

    File.rm_rf!(install_dir)
    File.mkdir_p!(Path.dirname(install_dir))
    File.mkdir_p!(work_dir)

    try do
      run_cmd!("git", ["clone", "https://github.com/crosstool-ng/crosstool-ng.git", source_dir])
      run_cmd!("git", ["checkout", ctng_tag], cd: source_dir)
      run_cmd!("bash", ["./bootstrap"], cd: source_dir)

      {configure_env, make_cmd} = ctng_build_environment()

      run_cmd!("bash", ["./configure", "--prefix=#{install_dir}"], cd: source_dir, env: configure_env)
      run_cmd!(make_cmd, [], cd: source_dir)
      run_cmd!(make_cmd, ["install"], cd: source_dir)

      ctng = Path.join([install_dir, "bin", "ct-ng"])

      if File.exists?(ctng) do
        ctng
      else
        missing_ctng!()
      end
    after
      File.rm_rf!(work_dir)
    end
  end

  defp ctng_build_environment do
    case :os.type() do
      {:unix, :darwin} ->
        brew_prefix = cmd_output!("brew", ["--prefix"])
        binutils_prefix = cmd_output!("brew", ["--prefix", "binutils"])
        ncurses_prefix = cmd_output!("brew", ["--prefix", "ncurses"])
        gcc_version = "15"

        env = [
          {"CC", "gcc-#{gcc_version}"},
          {"CXX", "g++-#{gcc_version}"},
          {"AR", "gcc-ar-#{gcc_version}"},
          {"NM", "gcc-nm-#{gcc_version}"},
          {"RANLIB", "gcc-ranlib-#{gcc_version}"},
          {"CPP", "cpp-#{gcc_version}"},
          {"OBJDUMP", Path.join(binutils_prefix, "bin/gobjdump")},
          {"OBJCOPY", Path.join(binutils_prefix, "bin/gobjcopy")},
          {"READELF", Path.join(binutils_prefix, "bin/greadelf")},
          {"CFLAGS", "-I#{brew_prefix}/include -I#{ncurses_prefix}/include"},
          {"LDFLAGS", "-L#{brew_prefix}/lib -lintl"},
          {"SED", Path.join(brew_prefix, "bin/gsed")},
          {"MAKE", Path.join(brew_prefix, "bin/gmake")}
        ]

        {env, Path.join(brew_prefix, "bin/gmake")}

      {:unix, :freebsd} ->
        {[{"SED", "/usr/local/bin/gsed"}, {"MAKE", "/usr/local/bin/gmake"}, {"PATCH", "/usr/local/bin/gpatch"}], "/usr/local/bin/gmake"}

      _ ->
        {[{"SED", "sed"}], "make"}
    end
  end

  defp run_cmd!(command, args, opts \\ []) do
    {output, status} =
      System.cmd(command, args, Keyword.merge([stderr_to_stdout: true], opts))

    if status == 0 do
      output
    else
      raise """
      command failed: #{Enum.join([command | args], " ")}

      #{output}
      """
    end
  end

  defp cmd_output!(command, args) do
    command
    |> run_cmd!(args)
    |> String.trim()
  end

  defp home_dir! do
    System.user_home() || raise "could not determine home directory"
  end
end

ToolchainVersionUpdater.main(System.argv())
